### PR TITLE
Vote Log File

### PR DESCRIPTION
**Pull request by Ichbinjoe**

### CODE REVIEW

**Comment by seadoggie01** [comment]
I've updated the Bukkit branch to have asynchronous file writing and the config has the path instead of a bool now. Let me know if you see any issues :)

**Comment by kikelkik** [comment]
Cool that you made a PR for this!
I'd really appreciate that vote logging feature. 

I have a question to your solution: 
Does the VoteLogListener also listen to failed vote events? It is quite important to recognize these 
`[Votifier NIO worker/ERROR]: [Votifier] Unable to process vote from ...` in that log file because nobody recognizes them in the server log which leads to players not getting their reward on failed votes later.

**Comment by Ichbinjoe** [comment]
@kikelkik due to how votifier works, if we can't process the vote then we don't know what originated the vote, who voted or anything. Likely if you set up your lists right, these are garbage / non votes talking to votifier anyways.

**Comment by kikelkik** [comment]
Alright, then why not accept this PR and merge into master? :)

**Comment by astei** [comment]
1. Because it doesn't work with all platforms NuVotifier supports. We support more than just Bukkit, it just so happens Bukkit is the most popular platform.
2. I have some concerns about the code quality.

Of these, number 1 is my biggest concern.

**Comment by astei** [comment]
Closing due to inactivity. I think this might be a better fit as a listener and not as core NuVotifier functionality.

**Pull request closed without merging**
